name: Deploy Prod configuration to Digital Ocean Staging

on:
  workflow_run:
    workflows: ["Create and publish a Docker image"]
    types: [completed]
    branches:
    - 'main'
    - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Digital Ocean droplet via SSH action
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.ACCESS_KEY }}
        script: |
            temp_env_file=$(mktemp)
            
            echo ${{secrets.COMPOSE_ENV}} >> $temp_env_file
            git clone ${{ env.GITHUB_SERVER_URL }}/${{ env.GITHUB_REPOSITORY }}.git socialpredict-deploy
            git checkout ${{ env.GITHUB_SHA }}
            cd socialpredict-deploy
            docker compose --env-file $temp_env_file -f ./scripts/docker-compose-prod.yaml up -d --no-deps frontend backend